### ISSUE TITLE
Podtail and Podalong patterns are invalid

### ISSUE THREAD

**Issue by benjaminbellamy** [opawg/podcast-rss-useragents#10]
Podtail and Podalong patterns look invalid and they do not seem to meet [User Agent String best practices](https://developers.whatismybrowser.com/learn/user-agent-best-practices/):
```
"pattern": "Mozilla\/5.0 (compatible; Podalong\/",
"pattern": "Mozilla\/5.0 (compatible; Podtail\/",
```
Parentheses are not matched.

**Comment by jamescridland** [comment]
Hi, Benjamin,

The parentheses aren't required to be matched. The `pattern` is just that - a pattern to watch for. In this case, their UAs start with the Mozilla declaration, and then their own name. Our standard is to avoid hard-coding any version numbers in the list.

In this case, they could be tightened-up to remove the Mozilla bits; I'll make a note to do that.

**Comment by benjaminbellamy** [comment]
Ok, so these are not meant to be regexp, my bad.

**Comment by benjaminbellamy** [comment]
I corrected [UserAgentsRSSGenerate.php](https://github.com/opawg/user-agents-php/blob/main/src/UserAgentsRSSGenerate.php) accordingly.

**Comment by jamescridland** [comment]
Sorry, I've confused things. They're supposed to be regexes. The parentheses here aren't supposed to be part of the regex, and they probably haven't been escaped properly?

I'm using:

```php
$audioua=json_decode(file_get_contents('https://raw.githubusercontent.com/opawg/user-agents/master/src/user-agents.json'),true);
foreach ($audioua AS $audioapp) {
 foreach ($audioapp['user_agents'] as $pattern) {
  $pattern=str_replace('/','\/',$pattern);
  preg_match('/'.$pattern.'/',$useragent,$output);
  if (sizeof($output)>0) {
   if ($audioapp['app']<>"") {
    $uasource=$uasource.$audioapp['app'].'<BR><small>(matches '.$pattern.')</small><BR>';
   }
  }
 }
}
```
...to cycle through the list. Does that help clarify?

**Comment by benjaminbellamy** [comment]
Then I guess we can close that issue! 🥳
