### ISSUE TITLE
Attribution for webapps - a proposal for an optional ?_from= audio querystring

### ISSUE THREAD

**Issue by jamescridland** [opawg/podcast-rss-useragents#12]
I'd like to propose a querystring for web apps to optionally use to assist with attribution.

## The problem

If I listen to a podcast on Podfriend on my Windows laptop, then this is the useragent that will present itself to my podcast host:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

Here's the useragent from a listen to a podcast within a Google Search result on that same laptop:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

...here I am listening to a podcast using Podchaser's inbuilt player:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

...here I am listening to a podcast on a clever embedded Twitter card:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

...and here is a podcast on the Apple Podcasts website:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

The observant among you will have spotted that these are all exactly the same. A podcast host is unable to differentiate between any of these plays, and a podcast host is left without any idea where their marketing has worked and which podcast service is driving the traffic to them.

The result? [Podtrac reports](https://podnews.net/update/downloads-and-audience-per-platform) that the second-most popular podcast player is... Google Chrome. Which it is. But it isn't.

## Another problem

If you hit 'play' in Pocket Casts on an iPhone but you haven't downloaded the audio first, the app will try to 'progressively download' the audio - or 'stream' it in commonly-used language. It does this using the AppleCoreMusic library, and to a podcast host, it looks like this:

`AppleCoreMedia/1.0.0.18A393 (iPhone; U; CPU OS 14_0_1 like Mac OS X; en_us)`

Hit 'play' in Apple Podcasts on an iPhone without downloading the file first? It looks like

`AppleCoreMedia/1.0.0.18A393 (iPhone; U; CPU OS 14_0_1 like Mac OS X; en_us)`

Hit 'play' in Airr, a new iPhone podcast app? It looks like

`AppleCoreMedia/1.0.0.18A393 (iPhone; U; CPU OS 14_0_1 like Mac OS X; en_us)`

And hit 'play' in Castro, and it looks like

`AppleCoreMedia/1.0.0.18A393 (iPhone; U; CPU OS 14_0_1 like Mac OS X; en_us)`

That's because this is the useragent of the library, and it can't be changed. Similar things happen on the Apple Watch.

The result? Podcast hosts either attribute all of this to Apple Podcasts (because it says the word 'Apple' in it), or they don't report it at all, or they break it out to 'AppleCoreMedia' which doesn't help anyone.

## Solutions

One solution is to use the `referer` HTTP header. But that doesn't always help with web-based plays (referers are often set to be blank for privacy; or report an email client or a social media service); and it doesn't help at all with the AppleCoreMedia problem.

Another solution is to give every podcast directory a different RSS feed which is bespoke to that platform. Some podcast hosts do this: but it isn't great to have lots of URLs floating around which have the same content with a different address (and is against best practice). It's also hard if you supply `https://example.com/rss/for-apple` into Apple Podcasts, and then Overcast goes and grabs that for its own use.

A better solution is to use the [RSS useragents](https://github.com/opawg/podcast-rss-useragents) repo - to spot the RSS calls being made, and then to add a query string to the audio. So, if your RSS feed is called by a useragent you recognise like `Overcast/1.0`, you can then set the audio to be `https://example.com/audio/mygreatpodcast.mp3?_from=overcast` and you can then be reasonably sure that any use of this audio is from Overcast - even in the web player it produces.

[Here is an example of the different useragents being used on a day's worth of data](https://podnews.net/_pages/podcast-analytics/parse-analytics.php). The RSS useragent approach works really well.

BUT Podcast Index throws a spanner in the works here. The Podcast Index RSS useragent starts `Podcastindex.org/` but that then means that every piece of audio that uses Podcast Index's API is tagged with `_from=podcastindex`. If twenty apps use Podcast Index's APIs, then those apps are invisible to podcasters, and we don't know which is performing best.

## The proposal

Podfriend is a web app. It's unable to modify the browser useragent, or to add any bespoke headers.

If it wishes to signal to a podcaster that "this play is coming from Podfriend", it could **send a unique indication in its request for the audio.**

My proposal is that this specific query string name is uniformly called `_from`, and the value should be an unambiguous name for the service or app - normally a domain or pseudo-domain (which we may, optionally, wish to list in [the OPAWG rss useragents list](https://github.com/opawg/podcast-rss-useragents). The use of the underscore in `_from` is unlikely to clash with anything.

So, as an example:
`https://example.com/audio/mygreatpodcast.mp3?_from=podfriend.com`

Where a querystring is already there, the query string should be appended with a `&`, like:
`https://example.com/audio/mygreatpodcast.mp3?version=45&_from=podfriend.com`

Adding this audio query string in a uniform fashion would enable any host or analytics service to spot this query string for analytics; and help developers get the credit they deserve. It would work whether the podcast is downloaded or streamed, and be unlikely to be stripped or removed. (Only iVoox, in my tests, seems to remove all query strings from audio URLs).

Most importantly, it would be the end of "the second most popular podcast platform is Google Chrome" - which is nonsense.

## What this means

The above will change the "slug" in the RSS useragents list to be a domain or pseudo-domain. Nobody ought to be in control of the slugs that are used; and this way it should allow more obvious ways to discover more about these services.

**Comment by benjaminbellamy** [comment]
I say let's go for it!
I would add a "domain" field (and then remove "slug" field) in https://github.com/opawg/podcast-rss-useragents/blob/master/src/rss-ua.json so that it is consistent and meaningful.
As soon as this is done I will update https://github.com/opawg/user-agents-php

**Comment by benjaminbellamy** [comment]
I am wondering: in case useragent is not recognized with podcast-rss-useragents, would it make sense to store instead the domain name from http_referer?

**Comment by jamescridland** [comment]
Referrers aren't that helpful, it turns out; there are surprisingly few in the audio requests that I see. But it might be interesting to try.

**Comment by jamescridland** [comment]
I've added `?_from=` to the main readme.

And I think I'm about to go through and switch the slugs to domains, once I've imported the latest data. Wish me luck...

**Comment by benjaminbellamy** [comment]
Good luck !
(I’ll switch too as soon as you told us you survived… ;-)
