### ISSUE TITLE
Incorrect attribution for Typhoeus

### ISSUE THREAD

**Issue by ziggythehamster** [opawg/podcast-rss-useragents#18]
I noticed this in the JSON file:

```
    {
        "pattern": "Typhoeus",
        "name": "Digital Podcast",
        "slug": "digitalpodcast.com",
        "url": "http:\/\/www.digitalpodcast.com\/"
    },
```

Typhoeus is a Ruby cURL library and that's the default user agent used by it; it's not possible to identify a specific service/app/etc. from Typhoeus alone.

**Comment by jamescridland** [comment]
That's very helpful, thanks. I'll remove that listing (and contact the folks at the podcast app)

**Comment by ziggythehamster** [comment]
It's super easy to change, just add `headers: { 'User-Agent' => 'YourApp/1.0 (+http://you.com)' }` to the options (second argument). It's easy to forget to do it, though, as we've got a couple of situations where we've only recently discovered (after several years) that we forgot to set the User-Agent :).

While they're in there, it's a good idea to add `accept_encoding: ''` (the empty string) to the _options_, if they haven't already, which instructs cURL to use compression if offered (empty string means "decompress anything this libcurl knows how to decompress"). You don't add that to the headers or else libcurl doesn't decompress on its own (it adds the header on its own). Typhoeus is a pretty thin wrapper around libcurl, so you have to have the libcurl man pages handy to figure out these more esoteric configuration options.

**Comment by jamescridland** [comment]
Thank you! Deleted.
