### ISSUE TITLE
Incorrect attribution for Faraday

### ISSUE THREAD

**Issue by ziggythehamster** [opawg/podcast-rss-useragents#19]
In the JSON, you have:

```
    {
        "pattern": "Faraday",
        "name": "Laughable",
        "slug": "laughable.com",
        "url": "https:\/\/laughable.com\/"
    },
```

Faraday is a Ruby library for doing HTTP requests, so you can't determine who is actually making requests using it absent other identifying information in the User-Agent.

**Comment by jamescridland** [comment]
Thanks! Deleted.
