### ISSUE TITLE
Indicate which RSS useragents report subscribers?

### ISSUE THREAD

**Issue by jerodsanto** [opawg/podcast-rss-useragents#27]
We find it super handy when feed crawlers report their subscribers to you like Overcast and some others do. Would you consider adding a `reportssubs` boolean field much like the `acceptsacc` field? I think this could:

1.  [Raise awareness](https://changelog.com/posts/an-open-letter-to-all-podcast-apps-except-overcast) of this very useful feature that podcast app developers can implement in their crawlers.
2. Help those of us [trying to collect and analyze this data](https://github.com/thechangelog/changelog.com/blob/master/lib/changelog/kits/agent_kit.ex#L2..L14) know which agents provide it and which don't.

That 2nd link shows which agents we at Changelog know report your subs. There may be more, though, which is why crowd sourcing this data would be great.

_(Thanks for maintaining this and the other datasets. Great stuff! 💚)_

**Comment by jamescridland** [comment]
That would be interesting, wouldn't it? Happy to add that if you'd like to add a PR, that sounds like useful data to have. (I do wonder how useful it is, but agree it could be interesting if more services supported it).

**Comment by jamescridland** [comment]
Thanks so much for the PR. This is really helpful information!
